// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/proto/backendPlugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMachineRequest_Size int32

const (
	CreateMachineRequest_NONE     CreateMachineRequest_Size = 0
	CreateMachineRequest_TINY     CreateMachineRequest_Size = 1
	CreateMachineRequest_SMALL    CreateMachineRequest_Size = 2
	CreateMachineRequest_MEDIUM   CreateMachineRequest_Size = 3
	CreateMachineRequest_LARGE    CreateMachineRequest_Size = 4
	CreateMachineRequest_ENORMOUS CreateMachineRequest_Size = 5
)

var CreateMachineRequest_Size_name = map[int32]string{
	0: "NONE",
	1: "TINY",
	2: "SMALL",
	3: "MEDIUM",
	4: "LARGE",
	5: "ENORMOUS",
}

var CreateMachineRequest_Size_value = map[string]int32{
	"NONE":     0,
	"TINY":     1,
	"SMALL":    2,
	"MEDIUM":   3,
	"LARGE":    4,
	"ENORMOUS": 5,
}

func (x CreateMachineRequest_Size) String() string {
	return proto.EnumName(CreateMachineRequest_Size_name, int32(x))
}

func (CreateMachineRequest_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{1, 0}
}

// Machine represents a single comet instance (vm/container/etc)
type Machine struct {
	// instance_id is the unique identifier for the particular backend being used
	// For example if this was AWS the instance_id would be the resource id
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// address is the note address for the comet, this is usually a DNS or IP
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// metadata is a key/value store for extra data that apps might want to store
	// per comet. This is a great place to store backend specific things like
	// virtual machine type(m5.4xlarge)
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{0}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Machine) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Machine) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateMachineRequest struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 CreateMachineRequest_Size `protobuf:"varint,3,opt,name=size,proto3,enum=proto.CreateMachineRequest_Size" json:"size,omitempty"`
	Metadata             map[string]string         `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateMachineRequest) Reset()         { *m = CreateMachineRequest{} }
func (m *CreateMachineRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMachineRequest) ProtoMessage()    {}
func (*CreateMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{1}
}

func (m *CreateMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineRequest.Unmarshal(m, b)
}
func (m *CreateMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineRequest.Marshal(b, m, deterministic)
}
func (m *CreateMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineRequest.Merge(m, src)
}
func (m *CreateMachineRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMachineRequest.Size(m)
}
func (m *CreateMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineRequest proto.InternalMessageInfo

func (m *CreateMachineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMachineRequest) GetSize() CreateMachineRequest_Size {
	if m != nil {
		return m.Size
	}
	return CreateMachineRequest_NONE
}

func (m *CreateMachineRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateMachineResponse struct {
	Machine *Machine `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	// status_message is used to provide additional information about a machine's
	// status
	StatusMessage        string   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMachineResponse) Reset()         { *m = CreateMachineResponse{} }
func (m *CreateMachineResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMachineResponse) ProtoMessage()    {}
func (*CreateMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{2}
}

func (m *CreateMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineResponse.Unmarshal(m, b)
}
func (m *CreateMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineResponse.Marshal(b, m, deterministic)
}
func (m *CreateMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineResponse.Merge(m, src)
}
func (m *CreateMachineResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMachineResponse.Size(m)
}
func (m *CreateMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineResponse proto.InternalMessageInfo

func (m *CreateMachineResponse) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

func (m *CreateMachineResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetPluginInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginInfoRequest) Reset()         { *m = GetPluginInfoRequest{} }
func (m *GetPluginInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoRequest) ProtoMessage()    {}
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{3}
}

func (m *GetPluginInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoRequest.Unmarshal(m, b)
}
func (m *GetPluginInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetPluginInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoRequest.Merge(m, src)
}
func (m *GetPluginInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoRequest.Size(m)
}
func (m *GetPluginInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoRequest proto.InternalMessageInfo

type GetPluginInfoResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// name of plugin
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// provider name e.g.(AWS, GCP, docker, etc)
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginInfoResponse) Reset()         { *m = GetPluginInfoResponse{} }
func (m *GetPluginInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoResponse) ProtoMessage()    {}
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{4}
}

func (m *GetPluginInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoResponse.Unmarshal(m, b)
}
func (m *GetPluginInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetPluginInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoResponse.Merge(m, src)
}
func (m *GetPluginInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoResponse.Size(m)
}
func (m *GetPluginInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoResponse proto.InternalMessageInfo

func (m *GetPluginInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetPluginInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPluginInfoResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CreateMachineRequest_Size", CreateMachineRequest_Size_name, CreateMachineRequest_Size_value)
	proto.RegisterType((*Machine)(nil), "proto.Machine")
	proto.RegisterMapType((map[string]string)(nil), "proto.Machine.MetadataEntry")
	proto.RegisterType((*CreateMachineRequest)(nil), "proto.CreateMachineRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.CreateMachineRequest.MetadataEntry")
	proto.RegisterType((*CreateMachineResponse)(nil), "proto.CreateMachineResponse")
	proto.RegisterType((*GetPluginInfoRequest)(nil), "proto.GetPluginInfoRequest")
	proto.RegisterType((*GetPluginInfoResponse)(nil), "proto.GetPluginInfoResponse")
}

func init() { proto.RegisterFile("backend/proto/backendPlugin.proto", fileDescriptor_16e734a482fe8dbd) }

var fileDescriptor_16e734a482fe8dbd = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0x8d, 0x09, 0x30, 0xd4, 0xc8, 0x1a, 0x91, 0xca, 0xa2, 0x91, 0x4a, 0x2d, 0x55, 0xa2,
	0x17, 0x22, 0xd1, 0x1e, 0xa2, 0xf6, 0x94, 0xb6, 0x56, 0x04, 0xc2, 0x50, 0x99, 0xe6, 0xd0, 0x53,
	0xb4, 0xc1, 0xd3, 0x64, 0x95, 0xb0, 0xa6, 0xde, 0x05, 0x29, 0xf9, 0xa1, 0x7e, 0x44, 0x2f, 0xfd,
	0xb4, 0x8a, 0xf5, 0xda, 0x0a, 0x91, 0x95, 0x5b, 0x4e, 0x9e, 0x79, 0x6f, 0xfd, 0xe6, 0xbd, 0x1d,
	0x1b, 0xde, 0x5e, 0xb2, 0xe5, 0x0d, 0x89, 0xe4, 0x78, 0x9d, 0xa5, 0x2a, 0x3d, 0x36, 0xdd, 0xf7,
	0xdb, 0xcd, 0x15, 0x17, 0x43, 0x8d, 0x61, 0x5d, 0x3f, 0x82, 0xbf, 0x16, 0x34, 0x22, 0xb6, 0xbc,
	0xe6, 0x82, 0xf0, 0x0d, 0xb4, 0xb9, 0x90, 0x8a, 0x89, 0x25, 0x5d, 0xf0, 0xc4, 0xb7, 0xfa, 0xd6,
	0xa0, 0x15, 0x43, 0x01, 0x8d, 0x13, 0xf4, 0xa1, 0xc1, 0x92, 0x24, 0x23, 0x29, 0x7d, 0x5b, 0x93,
	0x45, 0x8b, 0x27, 0xd0, 0x5c, 0x91, 0x62, 0x09, 0x53, 0xcc, 0xaf, 0xf5, 0x6b, 0x83, 0xf6, 0xe8,
	0x28, 0x9f, 0x33, 0x34, 0xe2, 0xc3, 0xc8, 0xd0, 0xa1, 0x50, 0xd9, 0x5d, 0x5c, 0x9e, 0xee, 0x7d,
	0x06, 0x77, 0x8f, 0x42, 0x0f, 0x6a, 0x37, 0x74, 0x67, 0xa6, 0xef, 0x4a, 0xec, 0x42, 0x7d, 0xcb,
	0x6e, 0x37, 0x64, 0x86, 0xe6, 0xcd, 0x27, 0xfb, 0xc4, 0x0a, 0xfe, 0xd9, 0xd0, 0xfd, 0x9a, 0x11,
	0x53, 0x64, 0xc6, 0xc4, 0xf4, 0x7b, 0x43, 0x52, 0x61, 0x07, 0xec, 0x32, 0x81, 0xcd, 0x13, 0x44,
	0x70, 0x04, 0x5b, 0x15, 0x0a, 0xba, 0xc6, 0x8f, 0xe0, 0x48, 0x7e, 0x4f, 0x7e, 0xad, 0x6f, 0x0d,
	0x3a, 0xa3, 0xbe, 0xf1, 0x5b, 0x25, 0x37, 0x5c, 0xf0, 0x7b, 0x8a, 0xf5, 0x69, 0x0c, 0x1f, 0x24,
	0x75, 0x74, 0xd2, 0xf7, 0x4f, 0xbd, 0xf9, 0x2c, 0xb1, 0x27, 0xe0, 0xec, 0x1c, 0x61, 0x13, 0x9c,
	0xd9, 0x7c, 0x16, 0x7a, 0x2f, 0x76, 0xd5, 0x8f, 0xf1, 0xec, 0xa7, 0x67, 0x61, 0x0b, 0xea, 0x8b,
	0xe8, 0x74, 0x3a, 0xf5, 0x6c, 0x04, 0x38, 0x88, 0xc2, 0x6f, 0xe3, 0xf3, 0xc8, 0xab, 0xed, 0xe0,
	0xe9, 0x69, 0x7c, 0x16, 0x7a, 0x0e, 0xbe, 0x84, 0x66, 0x38, 0x9b, 0xc7, 0xd1, 0xfc, 0x7c, 0xe1,
	0xd5, 0x83, 0x6b, 0x38, 0x7c, 0x64, 0x5c, 0xae, 0x53, 0x21, 0x09, 0x07, 0xd0, 0x58, 0xe5, 0x90,
	0x36, 0xd5, 0x1e, 0x75, 0xf6, 0x37, 0x1a, 0x17, 0x34, 0xbe, 0x83, 0x8e, 0x54, 0x4c, 0x6d, 0xe4,
	0xc5, 0x8a, 0xa4, 0x64, 0x57, 0x85, 0x63, 0x37, 0x47, 0xa3, 0x1c, 0x0c, 0x5e, 0x41, 0xf7, 0x8c,
	0x54, 0xfe, 0x11, 0x8e, 0xc5, 0xaf, 0xd4, 0x5c, 0x51, 0xc0, 0xe0, 0xf0, 0x11, 0x6e, 0x1c, 0xf8,
	0xd0, 0xd8, 0x52, 0x26, 0x79, 0x2a, 0xcc, 0xb5, 0x14, 0x6d, 0xe5, 0x3a, 0x7b, 0xd0, 0x5c, 0x67,
	0xe9, 0x96, 0x27, 0x94, 0xe9, 0x95, 0xb6, 0xe2, 0xb2, 0x1f, 0xfd, 0xb1, 0xc0, 0xfd, 0xf2, 0xf0,
	0x27, 0xc0, 0x09, 0xb8, 0x7b, 0xb1, 0xf1, 0xf5, 0x13, 0x5b, 0xec, 0x1d, 0x55, 0x93, 0xc6, 0xe7,
	0x04, 0xdc, 0xbd, 0x00, 0xa5, 0x56, 0x55, 0xdc, 0x52, 0xab, 0x32, 0xf3, 0xe5, 0x81, 0x26, 0x3f,
	0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xe6, 0x1f, 0xc5, 0xc2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendPluginClient is the client API for BackendPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendPluginClient interface {
	CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*CreateMachineResponse, error)
	// GetPluginInfo returns information about the backend plugin loaded
	// this is useful for debugging and logging
	GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error)
}

type backendPluginClient struct {
	cc *grpc.ClientConn
}

func NewBackendPluginClient(cc *grpc.ClientConn) BackendPluginClient {
	return &backendPluginClient{cc}
}

func (c *backendPluginClient) CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*CreateMachineResponse, error) {
	out := new(CreateMachineResponse)
	err := c.cc.Invoke(ctx, "/proto.BackendPlugin/CreateMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error) {
	out := new(GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.BackendPlugin/GetPluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendPluginServer is the server API for BackendPlugin service.
type BackendPluginServer interface {
	CreateMachine(context.Context, *CreateMachineRequest) (*CreateMachineResponse, error)
	// GetPluginInfo returns information about the backend plugin loaded
	// this is useful for debugging and logging
	GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error)
}

// UnimplementedBackendPluginServer can be embedded to have forward compatible implementations.
type UnimplementedBackendPluginServer struct {
}

func (*UnimplementedBackendPluginServer) CreateMachine(ctx context.Context, req *CreateMachineRequest) (*CreateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMachine not implemented")
}
func (*UnimplementedBackendPluginServer) GetPluginInfo(ctx context.Context, req *GetPluginInfoRequest) (*GetPluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}

func RegisterBackendPluginServer(s *grpc.Server, srv BackendPluginServer) {
	s.RegisterService(&_BackendPlugin_serviceDesc, srv)
}

func _BackendPlugin_CreateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).CreateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BackendPlugin/CreateMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).CreateMachine(ctx, req.(*CreateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BackendPlugin/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).GetPluginInfo(ctx, req.(*GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BackendPlugin",
	HandlerType: (*BackendPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMachine",
			Handler:    _BackendPlugin_CreateMachine_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _BackendPlugin_GetPluginInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/proto/backendPlugin.proto",
}
