// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/proto/backendPlugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMachineRequest_Size int32

const (
	CreateMachineRequest_NONE     CreateMachineRequest_Size = 0
	CreateMachineRequest_TINY     CreateMachineRequest_Size = 1
	CreateMachineRequest_SMALL    CreateMachineRequest_Size = 2
	CreateMachineRequest_MEDIUM   CreateMachineRequest_Size = 3
	CreateMachineRequest_LARGE    CreateMachineRequest_Size = 4
	CreateMachineRequest_ENORMOUS CreateMachineRequest_Size = 5
)

var CreateMachineRequest_Size_name = map[int32]string{
	0: "NONE",
	1: "TINY",
	2: "SMALL",
	3: "MEDIUM",
	4: "LARGE",
	5: "ENORMOUS",
}

var CreateMachineRequest_Size_value = map[string]int32{
	"NONE":     0,
	"TINY":     1,
	"SMALL":    2,
	"MEDIUM":   3,
	"LARGE":    4,
	"ENORMOUS": 5,
}

func (x CreateMachineRequest_Size) String() string {
	return proto.EnumName(CreateMachineRequest_Size_name, int32(x))
}

func (CreateMachineRequest_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{0, 0}
}

type CreateMachineRequest struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 CreateMachineRequest_Size `protobuf:"varint,3,opt,name=size,proto3,enum=proto.CreateMachineRequest_Size" json:"size,omitempty"`
	Owners               []string                  `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
	Metadata             map[string]string         `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateMachineRequest) Reset()         { *m = CreateMachineRequest{} }
func (m *CreateMachineRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMachineRequest) ProtoMessage()    {}
func (*CreateMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{0}
}

func (m *CreateMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineRequest.Unmarshal(m, b)
}
func (m *CreateMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineRequest.Marshal(b, m, deterministic)
}
func (m *CreateMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineRequest.Merge(m, src)
}
func (m *CreateMachineRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMachineRequest.Size(m)
}
func (m *CreateMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineRequest proto.InternalMessageInfo

func (m *CreateMachineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMachineRequest) GetSize() CreateMachineRequest_Size {
	if m != nil {
		return m.Size
	}
	return CreateMachineRequest_NONE
}

func (m *CreateMachineRequest) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *CreateMachineRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateMachineResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMachineResponse) Reset()         { *m = CreateMachineResponse{} }
func (m *CreateMachineResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMachineResponse) ProtoMessage()    {}
func (*CreateMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{1}
}

func (m *CreateMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineResponse.Unmarshal(m, b)
}
func (m *CreateMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineResponse.Marshal(b, m, deterministic)
}
func (m *CreateMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineResponse.Merge(m, src)
}
func (m *CreateMachineResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMachineResponse.Size(m)
}
func (m *CreateMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineResponse proto.InternalMessageInfo

type GetPluginInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginInfoRequest) Reset()         { *m = GetPluginInfoRequest{} }
func (m *GetPluginInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoRequest) ProtoMessage()    {}
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{2}
}

func (m *GetPluginInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoRequest.Unmarshal(m, b)
}
func (m *GetPluginInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetPluginInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoRequest.Merge(m, src)
}
func (m *GetPluginInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoRequest.Size(m)
}
func (m *GetPluginInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoRequest proto.InternalMessageInfo

type GetPluginInfoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginInfoResponse) Reset()         { *m = GetPluginInfoResponse{} }
func (m *GetPluginInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoResponse) ProtoMessage()    {}
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e734a482fe8dbd, []int{3}
}

func (m *GetPluginInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoResponse.Unmarshal(m, b)
}
func (m *GetPluginInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetPluginInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoResponse.Merge(m, src)
}
func (m *GetPluginInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoResponse.Size(m)
}
func (m *GetPluginInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.CreateMachineRequest_Size", CreateMachineRequest_Size_name, CreateMachineRequest_Size_value)
	proto.RegisterType((*CreateMachineRequest)(nil), "proto.CreateMachineRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.CreateMachineRequest.MetadataEntry")
	proto.RegisterType((*CreateMachineResponse)(nil), "proto.CreateMachineResponse")
	proto.RegisterType((*GetPluginInfoRequest)(nil), "proto.GetPluginInfoRequest")
	proto.RegisterType((*GetPluginInfoResponse)(nil), "proto.GetPluginInfoResponse")
}

func init() { proto.RegisterFile("backend/proto/backendPlugin.proto", fileDescriptor_16e734a482fe8dbd) }

var fileDescriptor_16e734a482fe8dbd = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4f, 0xe2, 0x60,
	0x10, 0xc7, 0xb7, 0x6f, 0x04, 0x66, 0x17, 0xd2, 0x4c, 0x58, 0xb6, 0x61, 0x3d, 0xd4, 0x9e, 0xea,
	0x05, 0x12, 0xf4, 0x60, 0xf4, 0x84, 0xda, 0x10, 0x08, 0x2d, 0xa6, 0xc8, 0xc1, 0xe3, 0x03, 0x1d,
	0xb5, 0x01, 0x9e, 0x62, 0x5b, 0x34, 0xf0, 0x85, 0xfc, 0x4a, 0x7e, 0x1c, 0xd3, 0x17, 0x89, 0x90,
	0x86, 0x53, 0x67, 0xfe, 0x33, 0xf3, 0xeb, 0x7f, 0x9e, 0x81, 0xd3, 0x29, 0x9b, 0xcd, 0x89, 0x7b,
	0xed, 0x55, 0x18, 0xc4, 0x41, 0x3b, 0xcf, 0xee, 0x17, 0xeb, 0x67, 0x9f, 0xb7, 0x52, 0x0d, 0x95,
	0xf4, 0x63, 0x7c, 0x8a, 0x50, 0xbf, 0x0d, 0x89, 0xc5, 0x64, 0xb3, 0xd9, 0x8b, 0xcf, 0xc9, 0xa5,
	0xd7, 0x35, 0x45, 0x31, 0xd6, 0x40, 0xf4, 0x3d, 0x4d, 0xd0, 0x05, 0xb3, 0xe2, 0x8a, 0xbe, 0x87,
	0x08, 0x32, 0x67, 0x4b, 0xd2, 0xc4, 0x54, 0x49, 0x63, 0xbc, 0x00, 0x39, 0xf2, 0xb7, 0xa4, 0x49,
	0xba, 0x60, 0xd6, 0x3a, 0x7a, 0x46, 0x6e, 0x15, 0xe1, 0x5a, 0x63, 0x7f, 0x4b, 0x6e, 0xda, 0x8d,
	0x0d, 0x28, 0x05, 0xef, 0x9c, 0xc2, 0x48, 0x93, 0x75, 0xc9, 0xac, 0xb8, 0x79, 0x86, 0x16, 0x94,
	0x97, 0x14, 0x33, 0x8f, 0xc5, 0x4c, 0x53, 0x74, 0xc9, 0xfc, 0xdd, 0x39, 0x3b, 0x46, 0xb4, 0xf3,
	0x5e, 0x8b, 0xc7, 0xe1, 0xc6, 0xdd, 0x8d, 0x36, 0xaf, 0xa1, 0xba, 0x57, 0x42, 0x15, 0xa4, 0x39,
	0x6d, 0xf2, 0x55, 0x92, 0x10, 0xeb, 0xa0, 0xbc, 0xb1, 0xc5, 0xfa, 0x7b, 0x99, 0x2c, 0xb9, 0x12,
	0x2f, 0x05, 0x63, 0x00, 0x72, 0xe2, 0x14, 0xcb, 0x20, 0x3b, 0x23, 0xc7, 0x52, 0x7f, 0x25, 0xd1,
	0x43, 0xdf, 0x79, 0x54, 0x05, 0xac, 0x80, 0x32, 0xb6, 0xbb, 0xc3, 0xa1, 0x2a, 0x22, 0x40, 0xc9,
	0xb6, 0xee, 0xfa, 0x13, 0x5b, 0x95, 0x12, 0x79, 0xd8, 0x75, 0x7b, 0x96, 0x2a, 0xe3, 0x1f, 0x28,
	0x5b, 0xce, 0xc8, 0xb5, 0x47, 0x93, 0xb1, 0xaa, 0x18, 0xff, 0xe0, 0xef, 0x81, 0xf1, 0x68, 0x15,
	0xf0, 0x88, 0x8c, 0x06, 0xd4, 0x7b, 0x14, 0x67, 0xd7, 0xe8, 0xf3, 0xa7, 0x20, 0xdf, 0x28, 0x19,
	0x38, 0xd0, 0xb3, 0x81, 0xce, 0x87, 0x00, 0xd5, 0x9b, 0x9f, 0x37, 0xc4, 0x01, 0x54, 0xf7, 0xd8,
	0xf8, 0xff, 0xc8, 0x53, 0x35, 0x4f, 0x8a, 0x8b, 0x19, 0x3d, 0x61, 0xed, 0xfd, 0x76, 0xc7, 0x2a,
	0x32, 0xb9, 0x63, 0x15, 0x3a, 0x9d, 0x96, 0xd2, 0xe2, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0x1c, 0x53, 0x2f, 0x81, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendPluginClient is the client API for BackendPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendPluginClient interface {
	CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*CreateMachineResponse, error)
	GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error)
}

type backendPluginClient struct {
	cc *grpc.ClientConn
}

func NewBackendPluginClient(cc *grpc.ClientConn) BackendPluginClient {
	return &backendPluginClient{cc}
}

func (c *backendPluginClient) CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*CreateMachineResponse, error) {
	out := new(CreateMachineResponse)
	err := c.cc.Invoke(ctx, "/proto.BackendPlugin/CreateMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error) {
	out := new(GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.BackendPlugin/GetPluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendPluginServer is the server API for BackendPlugin service.
type BackendPluginServer interface {
	CreateMachine(context.Context, *CreateMachineRequest) (*CreateMachineResponse, error)
	GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error)
}

// UnimplementedBackendPluginServer can be embedded to have forward compatible implementations.
type UnimplementedBackendPluginServer struct {
}

func (*UnimplementedBackendPluginServer) CreateMachine(ctx context.Context, req *CreateMachineRequest) (*CreateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMachine not implemented")
}
func (*UnimplementedBackendPluginServer) GetPluginInfo(ctx context.Context, req *GetPluginInfoRequest) (*GetPluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}

func RegisterBackendPluginServer(s *grpc.Server, srv BackendPluginServer) {
	s.RegisterService(&_BackendPlugin_serviceDesc, srv)
}

func _BackendPlugin_CreateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).CreateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BackendPlugin/CreateMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).CreateMachine(ctx, req.(*CreateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BackendPlugin/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).GetPluginInfo(ctx, req.(*GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BackendPlugin",
	HandlerType: (*BackendPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMachine",
			Handler:    _BackendPlugin_CreateMachine_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _BackendPlugin_GetPluginInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/proto/backendPlugin.proto",
}
